// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0tR7BvjA4b2juyzXR9M_RpVXeIh99ZhI',
    appId: '1:265891256267:web:82ca9ada3a3046f12ac84e',
    messagingSenderId: '265891256267',
    projectId: 'apimeteo-27e5c',
    authDomain: 'apimeteo-27e5c.firebaseapp.com',
    storageBucket: 'apimeteo-27e5c.firebasestorage.app',
    measurementId: 'G-KQ1YGKPW8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgnzOuCv7PZAA-8OiWJ9O9PUpbjSu44Oo',
    appId: '1:265891256267:android:f5441f250786d03a2ac84e',
    messagingSenderId: '265891256267',
    projectId: 'apimeteo-27e5c',
    storageBucket: 'apimeteo-27e5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWaFXXquvjDp0zD5GYE5-yBQpN9nEeaGE',
    appId: '1:265891256267:ios:686422e6e8aa9d1e2ac84e',
    messagingSenderId: '265891256267',
    projectId: 'apimeteo-27e5c',
    storageBucket: 'apimeteo-27e5c.firebasestorage.app',
    iosBundleId: 'com.palmertechnologia.testApiMeteo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWaFXXquvjDp0zD5GYE5-yBQpN9nEeaGE',
    appId: '1:265891256267:ios:686422e6e8aa9d1e2ac84e',
    messagingSenderId: '265891256267',
    projectId: 'apimeteo-27e5c',
    storageBucket: 'apimeteo-27e5c.firebasestorage.app',
    iosBundleId: 'com.palmertechnologia.testApiMeteo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0tR7BvjA4b2juyzXR9M_RpVXeIh99ZhI',
    appId: '1:265891256267:web:a9e1267d0e6ebd412ac84e',
    messagingSenderId: '265891256267',
    projectId: 'apimeteo-27e5c',
    authDomain: 'apimeteo-27e5c.firebaseapp.com',
    storageBucket: 'apimeteo-27e5c.firebasestorage.app',
    measurementId: 'G-WF733LSWR3',
  );
}
